[package]
name = "xsec"
version = "0.1.0"
edition = "2024"

[dependencies]
nautilus-core = { version = "0.61" }
nautilus-common = { version = "0.61" }
nautilus-model = { version = "0.61" }
nautilus-trading = { version = "0.61" }
nautilus-bybit = { version = "0.61" }
nautilus-backtest = { version = "0.61" }
nautilus-live = { version = "0.61" }
bon = "3.10.0"
anyhow = "1.0.104"
clap = { version = "4.6", features = ["derive"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
chrono = "0.4.45"
rmp-serde = "1"
log = "0.4.34"
rust_decimal = "1.43.0"
uuid = { version = "1.26", features = ["v7"] }

[dev-dependencies]
tempfile = "3"
