"""Render a QuantStats HTML tearsheet from a backtest run's CSV artifacts.

Usage:
    uv run analysis/tearsheet.py --uuid <RUN_ID>
    uv run analysis/tearsheet.py --latest

Reads ``runs/<RUN_ID>.portfolio.csv`` (the headline return series) and
``runs/<RUN_ID>.legs.csv`` (verified non-empty only), and writes
``runs/<RUN_ID>.tearsheet.html`` — a single self-contained file.

The Rust backtest binary writes those CSVs; the two languages share nothing but
the ``runs/`` directory. See ``analysis/README.md``.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RUNS_DIR = REPO_ROOT / "runs"


def _fail(message: str) -> "NoReturn":  # type: ignore[name-defined]
    print(f"error: {message}", file=sys.stderr)
    raise SystemExit(1)


def available_uuids() -> list[str]:
    """Run ids that have a legs CSV under ``runs/``, newest first."""
    legs = sorted(RUNS_DIR.glob("*.legs.csv"), key=lambda p: p.stat().st_mtime, reverse=True)
    return [p.name[: -len(".legs.csv")] for p in legs]


def resolve_uuid(args: argparse.Namespace) -> str:
    if args.latest:
        uuids = available_uuids()
        if not uuids:
            _fail(f"no runs found under {RUNS_DIR} (looked for *.legs.csv)")
        return uuids[0]
    return args.uuid


def load_returns(uuid: str):
    """Build the monthly net-return series QuantStats consumes."""
    import pandas as pd

    portfolio_path = RUNS_DIR / f"{uuid}.portfolio.csv"
    legs_path = RUNS_DIR / f"{uuid}.legs.csv"

    if not portfolio_path.exists():
        known = available_uuids()
        listing = "\n  ".join(known) if known else "(none)"
        _fail(f"unknown run '{uuid}': no {portfolio_path.name}. Available runs:\n  {listing}")

    if not legs_path.exists() or legs_path.stat().st_size == 0:
        _fail(f"legs CSV missing or empty for run {uuid} ({legs_path.name})")

    frame = pd.read_csv(portfolio_path)
    if frame.empty:
        _fail(f"portfolio CSV is empty for run {uuid}")
    if "net_return" not in frame.columns or "month" not in frame.columns:
        _fail(f"portfolio CSV for run {uuid} is missing 'month'/'net_return' columns")

    legs = pd.read_csv(legs_path)
    if legs.empty:
        _fail(f"legs CSV has a header but no rows for run {uuid}")

    # Month label 'YYYY-MM' -> month-end UTC timestamp.
    index = pd.to_datetime(frame["month"], format="%Y-%m") + pd.offsets.MonthEnd(0)
    series = pd.Series(frame["net_return"].astype(float).values, index=index, name="Strategy")
    series.index.name = "Date"
    return series.sort_index()


def render(uuid: str, returns) -> Path:
    try:
        import quantstats as qs
    except ImportError:
        _fail("quantstats is not installed — run `uv sync` inside analysis/")

    output = RUNS_DIR / f"{uuid}.tearsheet.html"
    title = f"X-Sectional Momentum — {uuid}"
    try:
        qs.reports.html(returns, output=str(output), title=title, download_filename=str(output))
    except TypeError:
        # Older/newer QuantStats signatures differ on kwargs.
        qs.reports.html(returns, output=str(output), title=title)

    if not output.exists() or output.stat().st_size == 0:
        _fail(f"QuantStats produced no output at {output}")

    # QuantStats' `title=` only sets the page heading; put the run id in <title>
    # too so an archived/mailed file is identifiable from the browser tab.
    html = output.read_text()
    html = html.replace(
        "<title>Tearsheet (generated by QuantStats)</title>",
        f"<title>{title}</title>",
        1,
    )
    output.write_text(html)
    return output


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--uuid", help="run id to render (keys runs/<uuid>.*)")
    group.add_argument("--latest", action="store_true", help="render the most recently modified run")
    args = parser.parse_args(argv)

    uuid = resolve_uuid(args)
    returns = load_returns(uuid)
    output = render(uuid, returns)
    print(f"wrote {output.relative_to(REPO_ROOT)}  ({len(returns)} months)")


if __name__ == "__main__":
    main()
